# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(764, 593)
        MainWindow.setMinimumSize(QtCore.QSize(650, 500))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mediaView = QtGui.QFrame(self.centralwidget)
        self.mediaView.setGeometry(QtCore.QRect(0, 0, 461, 231))
        self.mediaView.setStyleSheet(_fromUtf8(""))
        self.mediaView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mediaView.setFrameShadow(QtGui.QFrame.Raised)
        self.mediaView.setObjectName(_fromUtf8("mediaView"))
        self.subtitle = QtGui.QLabel(self.centralwidget)
        self.subtitle.setGeometry(QtCore.QRect(250, 240, 261, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subtitle.setFont(font)
        self.subtitle.setStyleSheet(_fromUtf8("color:white;"))
        self.subtitle.setText(_fromUtf8(""))
        self.subtitle.setObjectName(_fromUtf8("subtitle"))
        self.controlView = QtGui.QWidget(self.centralwidget)
        self.controlView.setGeometry(QtCore.QRect(30, 270, 661, 130))
        self.controlView.setMinimumSize(QtCore.QSize(510, 130))
        self.controlView.setMaximumSize(QtCore.QSize(16777215, 130))
        self.controlView.setObjectName(_fromUtf8("controlView"))
        self.verticalLayout = QtGui.QVBoxLayout(self.controlView)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setMargin(1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.timeDone = QtGui.QLabel(self.controlView)
        self.timeDone.setMinimumSize(QtCore.QSize(60, 0))
        self.timeDone.setMaximumSize(QtCore.QSize(60, 16777215))
        self.timeDone.setAlignment(QtCore.Qt.AlignCenter)
        self.timeDone.setObjectName(_fromUtf8("timeDone"))
        self.gridLayout_8.addWidget(self.timeDone, 0, 0, 1, 1)
        self.seekBar = QtGui.QSlider(self.controlView)
        self.seekBar.setMinimumSize(QtCore.QSize(365, 18))
        self.seekBar.setMaximumSize(QtCore.QSize(16777215, 18))
        self.seekBar.setOrientation(QtCore.Qt.Horizontal)
        self.seekBar.setObjectName(_fromUtf8("seekBar"))
        self.gridLayout_8.addWidget(self.seekBar, 0, 1, 1, 1)
        self.timeLeft = QtGui.QLabel(self.controlView)
        self.timeLeft.setMinimumSize(QtCore.QSize(60, 18))
        self.timeLeft.setMaximumSize(QtCore.QSize(60, 18))
        self.timeLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLeft.setObjectName(_fromUtf8("timeLeft"))
        self.gridLayout_8.addWidget(self.timeLeft, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setMargin(1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.muteButton = QtGui.QPushButton(self.controlView)
        self.muteButton.setMinimumSize(QtCore.QSize(30, 30))
        self.muteButton.setMaximumSize(QtCore.QSize(30, 30))
        self.muteButton.setText(_fromUtf8(""))
        self.muteButton.setObjectName(_fromUtf8("muteButton"))
        self.gridLayout_4.addWidget(self.muteButton, 0, 4, 1, 1)
        self.expansionWidget_3 = QtGui.QWidget(self.controlView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expansionWidget_3.sizePolicy().hasHeightForWidth())
        self.expansionWidget_3.setSizePolicy(sizePolicy)
        self.expansionWidget_3.setObjectName(_fromUtf8("expansionWidget_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.expansionWidget_3)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_4.addWidget(self.expansionWidget_3, 0, 1, 1, 1)
        self.volumeBar = QtGui.QSlider(self.controlView)
        self.volumeBar.setMinimumSize(QtCore.QSize(175, 0))
        self.volumeBar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.volumeBar.setOrientation(QtCore.Qt.Horizontal)
        self.volumeBar.setObjectName(_fromUtf8("volumeBar"))
        self.gridLayout_4.addWidget(self.volumeBar, 0, 5, 1, 1)
        self.mediaSettingsWidget = QtGui.QWidget(self.controlView)
        self.mediaSettingsWidget.setMinimumSize(QtCore.QSize(140, 60))
        self.mediaSettingsWidget.setMaximumSize(QtCore.QSize(140, 60))
        self.mediaSettingsWidget.setObjectName(_fromUtf8("mediaSettingsWidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.mediaSettingsWidget)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.fullscreenButton = QtGui.QPushButton(self.mediaSettingsWidget)
        self.fullscreenButton.setMinimumSize(QtCore.QSize(30, 30))
        self.fullscreenButton.setMaximumSize(QtCore.QSize(30, 30))
        self.fullscreenButton.setText(_fromUtf8(""))
        self.fullscreenButton.setObjectName(_fromUtf8("fullscreenButton"))
        self.horizontalLayout_6.addWidget(self.fullscreenButton)
        self.playlistButton = QtGui.QPushButton(self.mediaSettingsWidget)
        self.playlistButton.setMinimumSize(QtCore.QSize(30, 30))
        self.playlistButton.setMaximumSize(QtCore.QSize(30, 30))
        self.playlistButton.setText(_fromUtf8(""))
        self.playlistButton.setObjectName(_fromUtf8("playlistButton"))
        self.horizontalLayout_6.addWidget(self.playlistButton)
        self.stopButton = QtGui.QPushButton(self.mediaSettingsWidget)
        self.stopButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stopButton.setMaximumSize(QtCore.QSize(30, 30))
        self.stopButton.setText(_fromUtf8(""))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_6.addWidget(self.stopButton)
        self.gridLayout_4.addWidget(self.mediaSettingsWidget, 0, 0, 1, 1)
        self.mediaControlWidget = QtGui.QWidget(self.controlView)
        self.mediaControlWidget.setMinimumSize(QtCore.QSize(225, 70))
        self.mediaControlWidget.setMaximumSize(QtCore.QSize(225, 70))
        self.mediaControlWidget.setObjectName(_fromUtf8("mediaControlWidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.mediaControlWidget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.previous = QtGui.QPushButton(self.mediaControlWidget)
        self.previous.setMinimumSize(QtCore.QSize(40, 40))
        self.previous.setMaximumSize(QtCore.QSize(40, 40))
        self.previous.setText(_fromUtf8(""))
        self.previous.setObjectName(_fromUtf8("previous"))
        self.horizontalLayout_7.addWidget(self.previous)
        self.playState = QtGui.QPushButton(self.mediaControlWidget)
        self.playState.setMinimumSize(QtCore.QSize(50, 50))
        self.playState.setMaximumSize(QtCore.QSize(50, 50))
        self.playState.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("play-2.svg"))
        self.playState.setIcon(icon)
        self.playState.setObjectName(_fromUtf8("playState"))
        self.horizontalLayout_7.addWidget(self.playState)
        self.next = QtGui.QPushButton(self.mediaControlWidget)
        self.next.setMinimumSize(QtCore.QSize(40, 40))
        self.next.setMaximumSize(QtCore.QSize(40, 40))
        self.next.setText(_fromUtf8(""))
        self.next.setObjectName(_fromUtf8("next"))
        self.horizontalLayout_7.addWidget(self.next)
        self.gridLayout_4.addWidget(self.mediaControlWidget, 0, 2, 1, 1)
        self.expansionWidget_4 = QtGui.QWidget(self.controlView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expansionWidget_4.sizePolicy().hasHeightForWidth())
        self.expansionWidget_4.setSizePolicy(sizePolicy)
        self.expansionWidget_4.setObjectName(_fromUtf8("expansionWidget_4"))
        self.gridLayout_4.addWidget(self.expansionWidget_4, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 764, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPlayback = QtGui.QMenu(self.menubar)
        self.menuPlayback.setObjectName(_fromUtf8("menuPlayback"))
        self.menuSpeed = QtGui.QMenu(self.menuPlayback)
        self.menuSpeed.setObjectName(_fromUtf8("menuSpeed"))
        self.menu_Subtitles = QtGui.QMenu(self.menubar)
        self.menu_Subtitles.setObjectName(_fromUtf8("menu_Subtitles"))
        self.menu_Audio = QtGui.QMenu(self.menubar)
        self.menu_Audio.setObjectName(_fromUtf8("menu_Audio"))
        self.menu_Video = QtGui.QMenu(self.menubar)
        self.menu_Video.setObjectName(_fromUtf8("menu_Video"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_File = QtGui.QAction(MainWindow)
        self.actionOpen_File.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionOpen_File.setObjectName(_fromUtf8("actionOpen_File"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionOpen_Multiple_Files = QtGui.QAction(MainWindow)
        self.actionOpen_Multiple_Files.setObjectName(_fromUtf8("actionOpen_Multiple_Files"))
        self.actionAdd_Subtitle_File = QtGui.QAction(MainWindow)
        self.actionAdd_Subtitle_File.setObjectName(_fromUtf8("actionAdd_Subtitle_File"))
        self.actionJump_Forward = QtGui.QAction(MainWindow)
        self.actionJump_Forward.setObjectName(_fromUtf8("actionJump_Forward"))
        self.actionJump_Backward = QtGui.QAction(MainWindow)
        self.actionJump_Backward.setObjectName(_fromUtf8("actionJump_Backward"))
        self.actionX0_5 = QtGui.QAction(MainWindow)
        self.actionX0_5.setObjectName(_fromUtf8("actionX0_5"))
        self.actionX_1 = QtGui.QAction(MainWindow)
        self.actionX_1.setObjectName(_fromUtf8("actionX_1"))
        self.actionX_2 = QtGui.QAction(MainWindow)
        self.actionX_2.setObjectName(_fromUtf8("actionX_2"))
        self.actionX_4 = QtGui.QAction(MainWindow)
        self.actionX_4.setObjectName(_fromUtf8("actionX_4"))
        self.actionX_8 = QtGui.QAction(MainWindow)
        self.actionX_8.setObjectName(_fromUtf8("actionX_8"))
        self.actionAdd_Subtitle_Track = QtGui.QAction(MainWindow)
        self.actionAdd_Subtitle_Track.setObjectName(_fromUtf8("actionAdd_Subtitle_Track"))
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionPrevious = QtGui.QAction(MainWindow)
        self.actionPrevious.setObjectName(_fromUtf8("actionPrevious"))
        self.actionNext = QtGui.QAction(MainWindow)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionJump_to_specific_time = QtGui.QAction(MainWindow)
        self.actionJump_to_specific_time.setObjectName(_fromUtf8("actionJump_to_specific_time"))
        self.actionIncrease_Volume = QtGui.QAction(MainWindow)
        self.actionIncrease_Volume.setObjectName(_fromUtf8("actionIncrease_Volume"))
        self.actionDecrease_Volume = QtGui.QAction(MainWindow)
        self.actionDecrease_Volume.setObjectName(_fromUtf8("actionDecrease_Volume"))
        self.actionMute = QtGui.QAction(MainWindow)
        self.actionMute.setObjectName(_fromUtf8("actionMute"))
        self.actionFullscreen = QtGui.QAction(MainWindow)
        self.actionFullscreen.setCheckable(False)
        self.actionFullscreen.setObjectName(_fromUtf8("actionFullscreen"))
        self.actionShift_forward_by_1_second = QtGui.QAction(MainWindow)
        self.actionShift_forward_by_1_second.setObjectName(_fromUtf8("actionShift_forward_by_1_second"))
        self.actionShift_backward_by_1_second = QtGui.QAction(MainWindow)
        self.actionShift_backward_by_1_second.setObjectName(_fromUtf8("actionShift_backward_by_1_second"))
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionOpen_Multiple_Files)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSpeed.addAction(self.actionX0_5)
        self.menuSpeed.addAction(self.actionX_1)
        self.menuSpeed.addAction(self.actionX_2)
        self.menuSpeed.addAction(self.actionX_4)
        self.menuSpeed.addAction(self.actionX_8)
        self.menuPlayback.addAction(self.actionJump_Forward)
        self.menuPlayback.addAction(self.actionJump_Backward)
        self.menuPlayback.addAction(self.menuSpeed.menuAction())
        self.menuPlayback.addSeparator()
        self.menuPlayback.addAction(self.actionPlay)
        self.menuPlayback.addAction(self.actionStop)
        self.menuPlayback.addSeparator()
        self.menuPlayback.addAction(self.actionPrevious)
        self.menuPlayback.addAction(self.actionNext)
        self.menuPlayback.addSeparator()
        self.menuPlayback.addAction(self.actionJump_to_specific_time)
        self.menu_Subtitles.addAction(self.actionAdd_Subtitle_Track)
        self.menu_Subtitles.addSeparator()
        self.menu_Subtitles.addAction(self.actionShift_forward_by_1_second)
        self.menu_Subtitles.addAction(self.actionShift_backward_by_1_second)
        self.menu_Audio.addAction(self.actionIncrease_Volume)
        self.menu_Audio.addAction(self.actionDecrease_Volume)
        self.menu_Audio.addAction(self.actionMute)
        self.menu_Audio.addSeparator()
        self.menu_Video.addAction(self.actionFullscreen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlayback.menuAction())
        self.menubar.addAction(self.menu_Subtitles.menuAction())
        self.menubar.addAction(self.menu_Audio.menuAction())
        self.menubar.addAction(self.menu_Video.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.timeDone.setText(_translate("MainWindow", "00:00:00", None))
        self.timeLeft.setText(_translate("MainWindow", "00:00:00", None))
        self.muteButton.setToolTip(_translate("MainWindow", "volume", None))
        self.fullscreenButton.setToolTip(_translate("MainWindow", "Fullscreen", None))
        self.playlistButton.setToolTip(_translate("MainWindow", "Playlist", None))
        self.stopButton.setToolTip(_translate("MainWindow", "Stop", None))
        self.previous.setToolTip(_translate("MainWindow", "Previous", None))
        self.playState.setToolTip(_translate("MainWindow", "Play/Pause", None))
        self.next.setToolTip(_translate("MainWindow", "Next", None))
        self.menuFile.setTitle(_translate("MainWindow", "&Media", None))
        self.menuPlayback.setTitle(_translate("MainWindow", "P&layback", None))
        self.menuSpeed.setTitle(_translate("MainWindow", "&Speed", None))
        self.menu_Subtitles.setTitle(_translate("MainWindow", "&Subtitles", None))
        self.menu_Audio.setTitle(_translate("MainWindow", "&Audio ", None))
        self.menu_Video.setTitle(_translate("MainWindow", "&Video", None))
        self.actionOpen_File.setText(_translate("MainWindow", "&Open File", None))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionExit.setText(_translate("MainWindow", "&Exit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionOpen_Multiple_Files.setText(_translate("MainWindow", "Open &Multiple Files", None))
        self.actionOpen_Multiple_Files.setShortcut(_translate("MainWindow", "Ctrl+Shift+O", None))
        self.actionAdd_Subtitle_File.setText(_translate("MainWindow", "&Add Subtitle File", None))
        self.actionJump_Forward.setText(_translate("MainWindow", "&Jump Forward", None))
        self.actionJump_Forward.setShortcut(_translate("MainWindow", "Ctrl+Shift++", None))
        self.actionJump_Backward.setText(_translate("MainWindow", "Jump &Backward", None))
        self.actionJump_Backward.setShortcut(_translate("MainWindow", "Ctrl+Shift+-", None))
        self.actionX0_5.setText(_translate("MainWindow", "&x 0.5", None))
        self.actionX_1.setText(_translate("MainWindow", "&Normal Speed", None))
        self.actionX_2.setText(_translate("MainWindow", "x &2", None))
        self.actionX_4.setText(_translate("MainWindow", "x &4", None))
        self.actionX_8.setText(_translate("MainWindow", "x &8", None))
        self.actionAdd_Subtitle_Track.setText(_translate("MainWindow", "&Add Subtitle Track", None))
        self.actionPlay.setText(_translate("MainWindow", "&Play/Pause", None))
        self.actionPlay.setShortcut(_translate("MainWindow", "Space", None))
        self.actionPause.setText(_translate("MainWindow", "Pause", None))
        self.actionPause.setShortcut(_translate("MainWindow", "Space", None))
        self.actionStop.setText(_translate("MainWindow", "St&op", None))
        self.actionStop.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.actionPrevious.setText(_translate("MainWindow", "P&revious", None))
        self.actionPrevious.setShortcut(_translate("MainWindow", "Ctrl+Shift+Left", None))
        self.actionNext.setText(_translate("MainWindow", "&Next", None))
        self.actionNext.setShortcut(_translate("MainWindow", "Ctrl+Shift+Right", None))
        self.actionJump_to_specific_time.setText(_translate("MainWindow", "J&ump to specific time", None))
        self.actionJump_to_specific_time.setShortcut(_translate("MainWindow", "Ctrl+T", None))
        self.actionIncrease_Volume.setText(_translate("MainWindow", "&Increase Volume", None))
        self.actionIncrease_Volume.setShortcut(_translate("MainWindow", "Ctrl+Up", None))
        self.actionDecrease_Volume.setText(_translate("MainWindow", "&Decrease Volume", None))
        self.actionDecrease_Volume.setShortcut(_translate("MainWindow", "Ctrl+Down", None))
        self.actionMute.setText(_translate("MainWindow", "&Mute", None))
        self.actionMute.setShortcut(_translate("MainWindow", "M", None))
        self.actionFullscreen.setText(_translate("MainWindow", "&Fullscreen", None))
        self.actionFullscreen.setShortcut(_translate("MainWindow", "F", None))
        self.actionShift_forward_by_1_second.setText(_translate("MainWindow", "&Shift Forward By 1 Second", None))
        self.actionShift_forward_by_1_second.setShortcut(_translate("MainWindow", "H", None))
        self.actionShift_backward_by_1_second.setText(_translate("MainWindow", "Shift &Backward By 1 Second", None))
        self.actionShift_backward_by_1_second.setShortcut(_translate("MainWindow", "G", None))

