# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(764, 593)
        MainWindow.setMinimumSize(QtCore.QSize(650, 500))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mediaView = QtGui.QFrame(self.centralwidget)
        self.mediaView.setGeometry(QtCore.QRect(0, 0, 461, 231))
        self.mediaView.setStyleSheet(_fromUtf8(""))
        self.mediaView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mediaView.setFrameShadow(QtGui.QFrame.Raised)
        self.mediaView.setObjectName(_fromUtf8("mediaView"))
        self.controlView = QtGui.QFrame(self.centralwidget)
        self.controlView.setGeometry(QtCore.QRect(30, 270, 611, 130))
        self.controlView.setMinimumSize(QtCore.QSize(510, 130))
        self.controlView.setMaximumSize(QtCore.QSize(16777215, 130))
        self.controlView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.controlView.setFrameShadow(QtGui.QFrame.Raised)
        self.controlView.setObjectName(_fromUtf8("controlView"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.controlView)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.timeDone = QtGui.QLabel(self.controlView)
        self.timeDone.setMinimumSize(QtCore.QSize(60, 0))
        self.timeDone.setMaximumSize(QtCore.QSize(60, 16777215))
        self.timeDone.setAlignment(QtCore.Qt.AlignCenter)
        self.timeDone.setObjectName(_fromUtf8("timeDone"))
        self.gridLayout_5.addWidget(self.timeDone, 0, 0, 1, 1)
        self.seekBar = QtGui.QSlider(self.controlView)
        self.seekBar.setMinimumSize(QtCore.QSize(365, 18))
        self.seekBar.setMaximumSize(QtCore.QSize(16777215, 18))
        self.seekBar.setOrientation(QtCore.Qt.Horizontal)
        self.seekBar.setObjectName(_fromUtf8("seekBar"))
        self.gridLayout_5.addWidget(self.seekBar, 0, 1, 1, 1)
        self.timeLeft = QtGui.QLabel(self.controlView)
        self.timeLeft.setMinimumSize(QtCore.QSize(60, 18))
        self.timeLeft.setMaximumSize(QtCore.QSize(60, 18))
        self.timeLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLeft.setObjectName(_fromUtf8("timeLeft"))
        self.gridLayout_5.addWidget(self.timeLeft, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.expansionWidget_2 = QtGui.QWidget(self.controlView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expansionWidget_2.sizePolicy().hasHeightForWidth())
        self.expansionWidget_2.setSizePolicy(sizePolicy)
        self.expansionWidget_2.setObjectName(_fromUtf8("expansionWidget_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.expansionWidget_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_3.addWidget(self.expansionWidget_2, 0, 1, 1, 1)
        self.volumeBar = QtGui.QSlider(self.controlView)
        self.volumeBar.setMinimumSize(QtCore.QSize(175, 0))
        self.volumeBar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.volumeBar.setOrientation(QtCore.Qt.Horizontal)
        self.volumeBar.setObjectName(_fromUtf8("volumeBar"))
        self.gridLayout_3.addWidget(self.volumeBar, 0, 5, 1, 1)
        self.mediaSettingsWidget = QtGui.QWidget(self.controlView)
        self.mediaSettingsWidget.setMinimumSize(QtCore.QSize(140, 60))
        self.mediaSettingsWidget.setMaximumSize(QtCore.QSize(140, 60))
        self.mediaSettingsWidget.setObjectName(_fromUtf8("mediaSettingsWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.mediaSettingsWidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.fullscreenButton = QtGui.QPushButton(self.mediaSettingsWidget)
        self.fullscreenButton.setMinimumSize(QtCore.QSize(30, 30))
        self.fullscreenButton.setMaximumSize(QtCore.QSize(30, 30))
        self.fullscreenButton.setText(_fromUtf8(""))
        self.fullscreenButton.setObjectName(_fromUtf8("fullscreenButton"))
        self.horizontalLayout_4.addWidget(self.fullscreenButton)
        self.playlistButton = QtGui.QPushButton(self.mediaSettingsWidget)
        self.playlistButton.setMinimumSize(QtCore.QSize(30, 30))
        self.playlistButton.setMaximumSize(QtCore.QSize(30, 30))
        self.playlistButton.setText(_fromUtf8(""))
        self.playlistButton.setObjectName(_fromUtf8("playlistButton"))
        self.horizontalLayout_4.addWidget(self.playlistButton)
        self.stopButton = QtGui.QPushButton(self.mediaSettingsWidget)
        self.stopButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stopButton.setMaximumSize(QtCore.QSize(30, 30))
        self.stopButton.setText(_fromUtf8(""))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_4.addWidget(self.stopButton)
        self.setiingsButton = QtGui.QPushButton(self.mediaSettingsWidget)
        self.setiingsButton.setMinimumSize(QtCore.QSize(30, 30))
        self.setiingsButton.setMaximumSize(QtCore.QSize(30, 30))
        self.setiingsButton.setText(_fromUtf8(""))
        self.setiingsButton.setObjectName(_fromUtf8("setiingsButton"))
        self.horizontalLayout_4.addWidget(self.setiingsButton)
        self.gridLayout_3.addWidget(self.mediaSettingsWidget, 0, 0, 1, 1)
        self.mediaControlWidget = QtGui.QWidget(self.controlView)
        self.mediaControlWidget.setMinimumSize(QtCore.QSize(195, 70))
        self.mediaControlWidget.setMaximumSize(QtCore.QSize(195, 70))
        self.mediaControlWidget.setObjectName(_fromUtf8("mediaControlWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.mediaControlWidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.previous = QtGui.QPushButton(self.mediaControlWidget)
        self.previous.setMinimumSize(QtCore.QSize(40, 40))
        self.previous.setMaximumSize(QtCore.QSize(40, 40))
        self.previous.setText(_fromUtf8(""))
        self.previous.setObjectName(_fromUtf8("previous"))
        self.horizontalLayout_5.addWidget(self.previous)
        self.playState = QtGui.QPushButton(self.mediaControlWidget)
        self.playState.setMinimumSize(QtCore.QSize(50, 50))
        self.playState.setMaximumSize(QtCore.QSize(50, 50))
        self.playState.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("play-2.svg"))
        self.playState.setIcon(icon)
        self.playState.setObjectName(_fromUtf8("playState"))
        self.horizontalLayout_5.addWidget(self.playState)
        self.next = QtGui.QPushButton(self.mediaControlWidget)
        self.next.setMinimumSize(QtCore.QSize(40, 40))
        self.next.setMaximumSize(QtCore.QSize(40, 40))
        self.next.setText(_fromUtf8(""))
        self.next.setObjectName(_fromUtf8("next"))
        self.horizontalLayout_5.addWidget(self.next)
        self.gridLayout_3.addWidget(self.mediaControlWidget, 0, 2, 1, 1)
        self.expansionWidget = QtGui.QWidget(self.controlView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expansionWidget.sizePolicy().hasHeightForWidth())
        self.expansionWidget.setSizePolicy(sizePolicy)
        self.expansionWidget.setObjectName(_fromUtf8("expansionWidget"))
        self.gridLayout_3.addWidget(self.expansionWidget, 0, 3, 1, 1)
        self.muteButton = QtGui.QPushButton(self.controlView)
        self.muteButton.setMinimumSize(QtCore.QSize(30, 30))
        self.muteButton.setMaximumSize(QtCore.QSize(30, 30))
        self.muteButton.setText(_fromUtf8(""))
        self.muteButton.setObjectName(_fromUtf8("muteButton"))
        self.gridLayout_3.addWidget(self.muteButton, 0, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 764, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_File = QtGui.QAction(MainWindow)
        self.actionOpen_File.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionOpen_File.setObjectName(_fromUtf8("actionOpen_File"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionOpen_Multiple_Files = QtGui.QAction(MainWindow)
        self.actionOpen_Multiple_Files.setObjectName(_fromUtf8("actionOpen_Multiple_Files"))
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionOpen_Multiple_Files)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.timeDone.setText(_translate("MainWindow", "00:00:00", None))
        self.timeLeft.setText(_translate("MainWindow", "00:00:00", None))
        self.menuFile.setTitle(_translate("MainWindow", "&Media", None))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File", None))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionOpen_Multiple_Files.setText(_translate("MainWindow", "Open Multiple Files", None))

